import { Account, IncomeTransaction } from '@/components/financeapp/interfaces'
import {
  Bitcoin,
  Briefcase,
  Car,
  Clapperboard,
  CreditCard,
  GraduationCap,
  HeartPulse,
  Home,
  LandmarkIcon,
  MoreHorizontal,
  PawPrint,
  PiggyBank,
  Plane,
  ShoppingBag,
  ShoppingCart,
  TrendingUp,
  UtensilsCrossed,
} from 'lucide-react'

export const ICONS = [
  { name: 'account_balance', label: 'Checkings', icon: LandmarkIcon },
  { name: 'savings', label: 'Savings', icon: PiggyBank },
  { name: 'credit_card', label: 'Credit Card', icon: CreditCard },
  { name: 'trending_up', label: 'Investment', icon: TrendingUp },
  { name: 'crypto', label: 'Crypto', icon: Bitcoin },
  { name: 'shopping_cart', label: 'Shopping', icon: ShoppingCart },
  { name: 'shopping_bag', label: 'Shopping Bag', icon: ShoppingBag },
  { name: 'home', label: 'Home', icon: Home },
  { name: 'car', label: 'Car', icon: Car },
  { name: 'utensils', label: 'Dining', icon: UtensilsCrossed },
  { name: 'heart_pulse', label: 'Health', icon: HeartPulse },
  { name: 'clapperboard', label: 'Entertainment', icon: Clapperboard },
  { name: 'graduation_cap', label: 'Education', icon: GraduationCap },
  { name: 'plane', label: 'Travel', icon: Plane },
  { name: 'paw_print', label: 'Pets', icon: PawPrint },
  { name: 'briefcase', label: 'Work', icon: Briefcase },
  { name: 'more_horizontal', label: 'Other', icon: MoreHorizontal },
] as const

export const ACCOUNT_TYPES = [
  { value: 'savings', label: 'Savings Account' },
  { value: 'checking', label: 'Checking Account' },
  { value: 'investment', label: 'Investment' },
  { value: 'credit', label: 'Credit Card' },
  { value: 'cash', label: 'Cash / Wallet' },
] as const

export const CURRENCIES = [
  { value: 'USD', label: 'USD - US Dollar' },
  { value: 'EUR', label: 'EUR - Euro' },
  { value: 'GBP', label: 'GBP - British Pound' },
  { value: 'JPY', label: 'JPY - Japanese Yen' },
  { value: 'CAD', label: 'CAD - Canadian Dollar' },
] as const

export const EXPENSES = [
  {
    id: 1,
    date: '2023-10-24',
    time: '02:15 PM',
    payee: 'Starbucks Coffee #492',
    icon: 'coffee',
    category: 'Food & Drink',
    categoryColor: 'amber',
    amount: -6.5,
    receipt: true,
  },
  {
    id: 2,
    date: '2023-10-23',
    time: '10:00 AM',
    payee: 'Client Payment - Invoice #88',
    icon: 'payments',
    category: 'Income',
    categoryColor: 'emerald',
    amount: 2500,
    receipt: false,
  },
  {
    id: 3,
    date: '2023-10-22',
    time: '04:30 PM',
    payee: 'Apple Store - MacBook Pro Repair',
    icon: 'laptop_mac',
    category: 'Electronics',
    categoryColor: 'blue',
    amount: -1299,
    receipt: true,
  },
  {
    id: 4,
    date: '2023-10-21',
    time: '09:00 AM',
    payee: 'Monthly Rent Payment',
    icon: 'home',
    category: 'Housing',
    categoryColor: 'purple',
    amount: -2100,
    receipt: false,
  },
  {
    id: 5,
    date: '2023-10-20',
    time: '06:45 PM',
    payee: 'Whole Foods Market',
    icon: 'shopping_cart',
    category: 'Food & Drink',
    categoryColor: 'amber',
    amount: -184.22,
    receipt: true,
  },
  {
    id: 6,
    date: '2023-10-25',
    time: 'PENDING',
    payee: 'Shell Oil Station #22',
    icon: 'local_gas_station',
    category: 'Transport',
    categoryColor: 'slate',
    amount: -55,
    receipt: false,
    pending: true,
  },
]

export const INCOME: IncomeTransaction[] = [
  {
    id: 'inc_001',
    netAmount: 1500,
    grossAmount: 2000,
    medicareAmount: 29,
    federalTaxAmount: 250,
    FICAAmount: 124,
    hoursWorked: 80,
    hourlyRate: 25,
    overtimeHours: 10,
    overtimeRate: 37.5,
    payee: 'ACME Corp',
    notes: 'Bi-weekly paycheck',
    date: new Date('2026-02-01'),
    category: null,
    account: {
      id: 'acc_001',
      name: 'Checking Account',
    } as Account,
    userId: 'user_001',
  },
  {
    id: 'inc_002',
    netAmount: 1800,
    grossAmount: 2300,
    medicareAmount: 33,
    federalTaxAmount: 300,
    FICAAmount: 142,
    hoursWorked: 85,
    hourlyRate: 26,
    overtimeHours: 5,
    overtimeRate: 39,
    payee: 'Tech Solutions LLC',
    notes: 'Monthly salary',
    date: new Date('2026-02-15'),
    category: null,
    account: {
      id: 'acc_002',
      name: 'Savings Account',
    } as Account,
    userId: 'user_001',
  },
  {
    id: 'inc_003',
    netAmount: 900,
    grossAmount: 1200,
    medicareAmount: 17,
    federalTaxAmount: 120,
    FICAAmount: 74,
    hoursWorked: 40,
    hourlyRate: 30,
    overtimeHours: 0,
    overtimeRate: 45,
    payee: 'Freelance Client',
    notes: 'Contract work',
    date: new Date('2026-02-20'),
    category: null,
    account: {
      id: 'acc_001',
      name: 'Checking Account',
    } as Account,
    userId: 'user_001',
  },

  {
    id: 'inc_004',
    netAmount: 1200,
    grossAmount: 1500,
    medicareAmount: 22,
    federalTaxAmount: 150,
    FICAAmount: 86,
    hoursWorked: 60,
    hourlyRate: 25,
    overtimeHours: 0,
    overtimeRate: 37.5,
    payee: 'Tech Solutions LLC',
    notes: 'Monthly salary',
    date: new Date('2026-02-20'),
    category: null,
    account: {
      id: 'acc_002',
      name: 'Savings Account',
    } as Account,
    userId: 'user_001',
  },

  {
    id: 'inc_005',
    netAmount: 1200,
    grossAmount: 1500,
    medicareAmount: 22,
    federalTaxAmount: 150,
    FICAAmount: 86,
    hoursWorked: 60,
    hourlyRate: 25,
    overtimeHours: 0,
    overtimeRate: 37.5,
    payee: 'Tech Solutions LLC',
    notes: 'Monthly salary',
    date: new Date('2026-02-20'),
    category: null,
    account: {
      id: 'acc_002',
      name: 'Savings Account',
    } as Account,
    userId: 'user_001',
  },

  {
    id: 'inc_006',
    netAmount: 1200,
    grossAmount: 1500,
    medicareAmount: 22,
    federalTaxAmount: 150,
    FICAAmount: 86,
    hoursWorked: 60,
    hourlyRate: 25,
    overtimeHours: 0,
    overtimeRate: 37.5,
    payee: 'Tech Solutions LLC',
    notes: 'Monthly salary',
    date: new Date('2026-02-20'),
    category: null,
    account: {
      id: 'acc_002',
      name: 'Savings Account',
    } as Account,
    userId: 'user_001',
  },

  {
    id: 'inc_007',
    netAmount: 1200,
    grossAmount: 1500,
    medicareAmount: 22,
    federalTaxAmount: 150,
    FICAAmount: 86,
    hoursWorked: 60,
    hourlyRate: 25,
    overtimeHours: 0,
    overtimeRate: 37.5,
    payee: 'Tech Solutions LLC',
    notes: 'Monthly salary',
    date: new Date('2026-02-20'),
    category: null,
    account: {
      id: 'acc_002',
      name: 'Savings Account',
    } as Account,
    userId: 'user_001',
  },

  {
    id: 'inc_008',
    netAmount: 1200,
    grossAmount: 1500,
    medicareAmount: 22,
    federalTaxAmount: 150,
    FICAAmount: 86,
    hoursWorked: 60,
    hourlyRate: 25,
    overtimeHours: 0,
    overtimeRate: 37.5,
    payee: 'Tech Solutions LLC',
    notes: 'Monthly salary',
    date: new Date('2026-02-20'),
    category: null,
    account: {
      id: 'acc_002',
      name: 'Savings Account',
    } as Account,
    userId: 'user_001',
  },

  {
    id: 'inc_009',
    netAmount: 1200,
    grossAmount: 1500,
    medicareAmount: 22,
    federalTaxAmount: 150,
    FICAAmount: 86,
    hoursWorked: 60,
    hourlyRate: 25,
    overtimeHours: 0,
    overtimeRate: 37.5,
    payee: 'Tech Solutions LLC',
    notes: 'Monthly salary',
    date: new Date('2026-02-20'),
    category: null,
    account: {
      id: 'acc_002',
      name: 'Savings Account',
    } as Account,
    userId: 'user_001',
  },

  {
    id: 'inc_010',
    netAmount: 1200,
    grossAmount: 1500,
    medicareAmount: 22,
    federalTaxAmount: 150,
    FICAAmount: 86,
    hoursWorked: 60,
    hourlyRate: 25,
    overtimeHours: 0,
    overtimeRate: 37.5,
    payee: 'Tech Solutions LLC',
    notes: 'Monthly salary',
    date: new Date('2026-02-20'),
    category: null,
    account: {
      id: 'acc_002',
      name: 'Savings Account',
    } as Account,
    userId: 'user_001',
  },

  {
    id: 'inc_011',
    netAmount: 1200,
    grossAmount: 1500,
    medicareAmount: 22,
    federalTaxAmount: 150,
    FICAAmount: 86,
    hoursWorked: 60,
    hourlyRate: 25,
    overtimeHours: 0,
    overtimeRate: 37.5,
    payee: 'Tech Solutions LLC',
    notes: 'Monthly salary',
    date: new Date('2026-02-20'),
    category: null,
    account: {
      id: 'acc_002',
      name: 'Savings Account',
    } as Account,
    userId: 'user_001',
  },

  {
    id: 'inc_012',
    netAmount: 1200,
    grossAmount: 1500,
    medicareAmount: 22,
    federalTaxAmount: 150,
    FICAAmount: 86,
    hoursWorked: 60,
    hourlyRate: 25,
    overtimeHours: 0,
    overtimeRate: 37.5,
    payee: 'Tech Solutions LLC',
    notes: 'Monthly salary',
    date: new Date('2026-02-20'),
    category: null,
    account: {
      id: 'acc_002',
      name: 'Savings Account',
    } as Account,
    userId: 'user_001',
  },

  {
    id: 'inc_013',
    netAmount: 1200,
    grossAmount: 1500,
    medicareAmount: 22,
    federalTaxAmount: 150,
    FICAAmount: 86,
    hoursWorked: 60,
    hourlyRate: 25,
    overtimeHours: 0,
    overtimeRate: 37.5,
    payee: 'Tech Solutions LLC',
    notes: 'Monthly salary',
    date: new Date('2026-02-20'),
    category: null,
    account: {
      id: 'acc_002',
      name: 'Savings Account',
    } as Account,
    userId: 'user_001',
  },

  {
    id: 'inc_014',
    netAmount: 1200,
    grossAmount: 1500,
    medicareAmount: 22,
    federalTaxAmount: 150,
    FICAAmount: 86,
    hoursWorked: 60,
    hourlyRate: 25,
    overtimeHours: 0,
    overtimeRate: 37.5,
    payee: 'Tech Solutions LLC',
    notes: 'Monthly salary',
    date: new Date('2026-02-20'),
    category: null,
    account: {
      id: 'acc_002',
      name: 'Savings Account',
    } as Account,
    userId: 'user_001',
  },
]

export const CATEGORY_COLORS = {
  amber: {
    badge:
      'bg-amber-100 dark:bg-amber-900/30 text-amber-600 dark:text-amber-400 border-amber-200 dark:border-amber-900/50',
  },
  emerald: {
    badge:
      'bg-emerald-100 dark:bg-emerald-900/30 text-emerald-600 dark:text-emerald-400 border-emerald-200 dark:border-emerald-900/50',
  },
  blue: {
    badge:
      'bg-blue-100 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 border-blue-200 dark:border-blue-900/50',
  },
  purple: {
    badge:
      'bg-purple-100 dark:bg-purple-900/30 text-purple-600 dark:text-purple-400 border-purple-200 dark:border-purple-900/50',
  },
  slate: {
    badge:
      'bg-slate-200 dark:bg-slate-800 text-slate-600 dark:text-slate-400 border-slate-300 dark:border-slate-700',
  },
}

export const INCOME_COLS = [
  'Date',
  'Category',
  'Net Pay',
  'Hours',
  'OT Hrs',
  'Federal',
  'FICA',
  'Medicare',
  'Gross',
  '$/Hr',
  '$/OT',
]
