import { beforeEach, describe, expect, it, vi } from 'vitest'
const mocks = vi.hoisted(() => ({ getSession: vi.fn(), createBudgetItem: vi.fn(), updateBudgetItem: vi.fn(), deleteBudgetItem: vi.fn(), createBudgetGroup: vi.fn(), updateBudgetGroup: vi.fn(), deleteBudgetGroup: vi.fn(), revalidatePath: vi.fn(), headers: vi.fn() }))
vi.mock('@/lib/auth', () => ({ auth: { api: { getSession: mocks.getSession } } }))
vi.mock('@/repository/budget', () => ({ createBudgetItem: mocks.createBudgetItem, updateBudgetItem: mocks.updateBudgetItem, deleteBudgetItem: mocks.deleteBudgetItem, createBudgetGroup: mocks.createBudgetGroup, updateBudgetGroup: mocks.updateBudgetGroup, deleteBudgetGroup: mocks.deleteBudgetGroup }))
vi.mock('next/cache', () => ({ revalidatePath: mocks.revalidatePath }))
vi.mock('next/headers', () => ({ headers: mocks.headers }))
import { createBudgetItemAction, deleteBudgetGroupAction, updateBudgetGroupAction } from '@/actions/budget/budget-item'
const budgetId = '00000000-0000-0000-0000-000000000001'; const groupId = '00000000-0000-0000-0000-000000000002'
describe('budget item actions', () => { beforeEach(() => { vi.clearAllMocks(); mocks.headers.mockResolvedValue({}); mocks.getSession.mockResolvedValue({ user: { id: 'user-1' } }) }); it('passes the authenticated owner when creating an item', async () => { mocks.createBudgetItem.mockResolvedValue({ id: 'item' }); await expect(createBudgetItemAction({ groupId, name: 'Salary', plannedAmount: 1 }, budgetId)).resolves.toMatchObject({ success: true }); expect(mocks.createBudgetItem).toHaveBeenCalledWith(expect.anything(), 'user-1') }); it('renames a group through the authenticated repository boundary', async () => { mocks.updateBudgetGroup.mockResolvedValue({ id: groupId, name: 'Home' }); await expect(updateBudgetGroupAction({ id: groupId, name: 'Home' }, budgetId)).resolves.toMatchObject({ success: true }); expect(mocks.updateBudgetGroup).toHaveBeenCalledWith({ id: groupId, name: 'Home' }, budgetId, 'user-1') }); it('surfaces the final-income-group guard', async () => { mocks.deleteBudgetGroup.mockRejectedValue(new Error('A budget must include at least one income group')); await expect(deleteBudgetGroupAction(groupId, budgetId)).resolves.toMatchObject({ success: false, status: 500 }) }) })
